# Generated by Django 5.0.2 on 2024-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodelo',
            name='comunidade',
            field=models.BooleanField(default=False, verbose_name='Comunidade'),
        ),
        migrations.AlterField(
            model_name='imovei',
            name='endereco',
            field=models.CharField(max_length=180, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='email',
            field=models.EmailField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='ocupacao',
            field=models.CharField(max_length=200, verbose_name='Ocupação'),
        ),
    ]
