# Generated by Django 4.1.7 on 2023-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locatario',
            constraint=models.UniqueConstraint(fields=('CPF', 'do_locador'), name='cpf_locatario_por_usuario'),
        ),
    ]
