# Generated by Django 4.2 on 2023-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_lida',
            field=models.DateTimeField(null=True),
        ),
    ]
