# Generated by Django 4.1.7 on 2023-03-16 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_locatario_cpf_locatario_por_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='CPF',
            field=models.CharField(blank=True, help_text='Digite apenas números', max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')]),
        ),
        migrations.AddConstraint(
            model_name='imovei',
            constraint=models.UniqueConstraint(fields=('nome', 'do_locador'), name='nome_imovel_por_usuario'),
        ),
    ]
