# Generated by Django 4.1.7 on 2023-03-16 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_usuario_cpf_imovei_nome_imovel_por_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Digite apenas números', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')]),
        ),
    ]
