# Generated by Django 4.1.7 on 2023-03-30 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contratomodelo_variaveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratodocconfig',
            name='fiador_CPF',
            field=models.CharField(blank=True, help_text='Digite apenas números', max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='contratodocconfig',
            name='fiador_RG',
            field=models.CharField(blank=True, help_text='Digite apenas números', max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='contratodocconfig',
            name='fiador_estadocivil',
            field=models.IntegerField(blank=True, choices=[(0, 'Solteiro(a)'), (1, 'Casado(a)'), (2, 'Separado(a)'), (3, 'Divorciado(a)'), (4, 'Viuvo(a)')], null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='contratodocconfig',
            name='fiador_nacionalidade',
            field=models.CharField(blank=True, default='Brasileiro(a)', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contratodocconfig',
            name='fiador_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='contratodocconfig',
            name='fiador_ocupacao',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='Ocupação'),
        ),
        migrations.AddField(
            model_name='contratodocconfig',
            name='tipo_de_locacao',
            field=models.IntegerField(blank=True, choices=[(0, 'residencial'), (1, 'não residencial')], null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='contratomodelo',
            name='titulo',
            field=models.CharField(help_text='Titulo', max_length=120, verbose_name=''),
        ),
    ]
