# Generated by Django 4.1.7 on 2023-03-31 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contratodocconfig_fiador_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratodocconfig',
            name='caucao',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')], verbose_name='Valor do caução'),
        ),
        migrations.AlterField(
            model_name='contratodocconfig',
            name='fiador_CPF',
            field=models.CharField(blank=True, help_text='Digite apenas números', max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='contratodocconfig',
            name='fiador_RG',
            field=models.CharField(blank=True, help_text='Digite apenas números', max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')], verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='contratodocconfig',
            name='fiador_nacionalidade',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='contratodocconfig',
            name='tipo_de_locacao',
            field=models.IntegerField(blank=True, choices=[(None, '-----------'), (1, 'residencial'), (2, 'não residencial')], null=True, verbose_name='Tipo de Locação'),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='telefone1',
            field=models.CharField(help_text='Celular/Digite apenas números', max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')], verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='telefone2',
            field=models.CharField(blank=True, help_text='Celular/Digite apenas números', max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')], verbose_name='Telefone 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Celular/Digite apenas números', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')]),
        ),
    ]
