# Generated by Django 4.1.7 on 2023-03-31 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contratodocconfig_caucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratodocconfig',
            name='caucao',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3), django.core.validators.RegexValidator(message='Digite apenas números.', regex='^[0-9]*$')]),
        ),
    ]
