# Generated by Django 4.1.7 on 2023-03-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
