# Generated by Django 4.1.7 on 2023-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contratodocconfig_caucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratodocconfig',
            name='fiador_endereco_completo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço Completo'),
        ),
    ]
