# Generated by Django 4.1.7 on 2023-03-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tarefa_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='tipo',
        ),
    ]
