# Generated by Django 4.1.7 on 2023-04-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contratodocconfig_fiador_endereco_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomodelo',
            name='condicoes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
