# Generated by Django 4.1.7 on 2023-04-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contratomodelo_condicoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodelo',
            name='condicoes',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='contratomodelo',
            name='variaveis',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
