# Generated by Django 4.1.7 on 2023-04-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contratomodelo_condicoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodelo',
            name='condicoes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratomodelo',
            name='variaveis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
