# Generated by Django 4.1.7 on 2023-04-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_contratomodelo_condicoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locatario',
            name='endereco_completo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço Completo'),
        ),
    ]
